import Head from "next/head";
import Image from "next/image";
import AboutUs from "../components/AboutUs";
import ContactUs from "../components/ContactUs";
import FooterSection from "../components/FooterSection";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Project from "../components/Project";
import Service from "../components/Service";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white dark:bg-gray-800">
        <Header />
        <Hero />
        <AboutUs />
        <Service />
        <Project />
        <ContactUs />
        <FooterSection />
      </main>
    </div>
  );
}
